---
 - hosts: all
   tasks:
     - debug:
         msg: "Running from Ansible Tower/Controller"

     - yum:
         name: httpd
         state: present
       register: result

     - debug:
         msg: result
